
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.define "es01" do |es01|
		es01.vm.box = "ubuntu/bionic64"
		es01.vm.hostname = "es01"
		es01.vm.network "private_network", ip: "192.168.33.100"
	end
  end


  
